# Generated by Django 6.0 on 2026-08-30 12:41

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('long_url', models.TextField()),
                ('delete_token', models.CharField(default=secrets.token_hex, max_length=64)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
